name: Build and Run Tests with Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Cache Maven
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              maven-${{ runner.os }}-

      - name: Set Executable Permissions (For Windows Self-Hosted Runners)
        if: runner.os == 'Windows'
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process

      - name: Run Smoke Tests
        run: mvn clean test -B -Dbrowser=chrome -DsuiteXmlFiles=src/test/resources/smoke.xml
        continue-on-error: true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Archive test results
        if: always()
        run: |
          zip -r report.zip target/surefire-reports/*.xml target/allure-results

      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4

      - name: Unzip test results
        run: |
          ls -la
          find . -name '*.zip' -execdir unzip '{}' \;

      - name: Aggregate Allure results
        run: |
          mkdir -p aggregated-allure-results
          find . -type d -name 'allure-results' -exec sh -c 'cp -r "$0"/* aggregated-allure-results/' {} \;
          rm -rf report-*/allure-results

      - name: Generate subfolder name from workflow name
        id: subfolder
        run: |
          echo "subfolder=$(echo $GITHUB_WORKFLOW | sed -E 's/[^a-zA-Z0-9]+/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Load test report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: aggregated-allure-results
          allure_report: allure-report
          subfolder: ${{ steps.subfolder.outputs.subfolder }}
          keep_reports: '20'
          report_url: "https://github.com/lidlisovskaya/test-project/${{ steps.subfolder.outputs.subfolder }}"

      - name: Publish test report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./gh-pages/${{ steps.subfolder.outputs.subfolder }}
          publish_branch: gh-pages
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'

      - name: Generate report link in summary
        run: |
          echo "## Allure Report " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # Blank line
          echo "[ View Allure Report](https://github.com/lidlisovskaya/test-project/${{ steps.subfolder.outputs.subfolder }})" >> $GITHUB_STEP_SUMMARY